##########################################
# TemplateEngine - example configuration #
##########################################

# These are example definition of Router component.
# In order to use the component, you first must call TemplateEngine::setConfig($pathToYourConfig).
TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: false
            CacheDir: '/var/tmp/smarty/cache'
            CompileDir: '/var/tmp/smarty/compile'
            TemplateDir: '/var/www/theme/templates'
            AutoEscapeOutput: false
            MergeCompiledIncludes: true
    # You can overwrite the default driver by providing your own.
    # How to create a new driver, read in the Readme.md file.
    # If you don't wish to change the default driver,
    # just ommit this definition in your config file.
    Bridges:
        Smarty: \Webiny\Component\TemplateEngine\Bridge\Smarty\Smarty
    # You don't need this part if you are using Composer autoload.
    ClassLoader:
        Smarty_:
            Path: '/var/www/Vendors/Smarty/libs/sysplugins'
            Normalize: false
            Case: lower